baseurl = "/"
title = "Non-Abelian Soup"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  subtitle = "This is a math blog... I guess?"
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  rss = true

[Author]
  name = "Peter Huxford"
  website = "https://nonabeliansoup.com"
  email = "pjhuxford@gmail.com"
  github = "pjhuxford"
  twitter = "pjhuxford"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about"
    weight = 2